[phases.setup]
nixPkgs = ['php82', 'php82Extensions.pdo_mysql', 'nodejs_18']

[phases.build]
cmds = [
    'composer install --ignore-platform-reqs --no-dev --optimize-autoloader',
    'npm ci || npm install',
    'npm run build'
]

# Pindahkan migrasi & caching ke tahap deployment / startup
[phases.deploy]
cmds = [
    'php artisan config:cache',
    'php artisan route:cache',
    'php artisan view:cache'
]

[start]
cmd = 'php artisan migrate --force && vendor/bin/heroku-php-nginx -p $PORT public/'